apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    env: dev
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: sample-app
  template:
    metadata:
      labels:
        env: dev
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: gcr.io/adolfo-test/hello-app:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
