steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['clean', 'assemble']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME', '.']
images:
- 'gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME'
