steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['clean']
  
- name: 'gcr.io/cloud-builders/gradle'
  args: ['assemble']
  
- name: 'gcr.io/cloud-builders/gradle'
  args: ['test']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME.$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Here's a convenient pattern to use for embedding shell scripts in cloudbuild.yaml."
    echo "This step only pushes an image if this build was triggered by a push to master."
    [[ "$BRANCH_NAME" == "master" ]] || [[ "$BRANCH_NAME" == "develop" ]] && docker push gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME.$BUILD_ID || echo "skipping . . ."
    
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] || [[ "$BRANCH_NAME" == "develop" ]] && sed -i.bak 's#gcr.io/adolfo-test/hello-app:feature-1.d82c128c-7870-4174-b3d9-663342180f93#gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME.$BUILD_ID#' ./k8s/ist/*.yaml && /builder/kubectl.bash apply -f k8s/ist/ist-deployment.yaml || echo "skipping . . ."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ingress-test1' 
 
    #deployment test
