steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'ssh', '--ssh-key-file', 'ssh-keys/public-ssh-keys.txt', 'test', '--project', 'adolfo-test', '--zone', 'us-central1-b', '--command', 'ps -ejH', '--dry-run'] 



