steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['clean', 'assemble']
  
- name: 'gcr.io/cloud-builders/gradle'
  args: ['test']
  id: gradle-test
  
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'  
  args: 
  - '-DskipTests=true'
  - '-Dsonar.host.url=https://az-sonar.ellisdon.com'
  - '-Dsonar.login=f0e0fe18041c87c225c7249212ffe90f298d1e9e'
  - '-Dsonar.projectKey=CompContactGCP'
  - '-Dsonar.sources=.'
  - '-Dsonar.java.binaries=.'
  - '-X'
  id: sonar-test
  env:
  - 'SONAR_SCANNER_OPTS=-Djavax.net.ssl.keyStore=keystore2.jks -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStore=keystore2.jks'
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME.$BUILD_ID', '.']
  waitFor: 
  - gradle-test
  - sonar-test

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "This step only pushes an image if this build was triggered by a push to master or develop"
    [[ "$BRANCH_NAME" == "master" ]] || [[ "$BRANCH_NAME" == "develop" ]] && docker push gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME.$BUILD_ID || echo "skipping . . ."  
    
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "This step only deployes the container image on the GKE (ist) if this build was triggered by a push develop"
    [[ "$BRANCH_NAME" == "develop" ]] && sed -i.bak 's#gcr.io/adolfo-test/hello-app:feature-1.d82c128c-7870-4174-b3d9-663342180f93#gcr.io/$PROJECT_ID/hello-app:latest#' ./k8s/dev/*.yaml && /builder/kubectl.bash apply -f k8s/dev/dev-deployment.yaml || echo "skipping . . ."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ingress-test1' 
  
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "This step only deployes the container image on the GKE (ist) if this build was triggered by a push to master"
    [[ "$BRANCH_NAME" == "master" ]] && sed -i.bak 's#gcr.io/adolfo-test/hello-app:feature-1.d82c128c-7870-4174-b3d9-663342180f93#gcr.io/$PROJECT_ID/hello-app:$BRANCH_NAME.$BUILD_ID#' ./k8s/dev/*.yaml && /builder/kubectl.bash apply -f k8s/dev/dev-deployment.yaml || echo "skipping . . ."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ingress-test1' 
 
    #deployment test after building the kubectl builder

