steps:

- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image-project cos-cloud --image-family cos-stable
    - ZONE=northamerica-northeast1-a	
    - USERNAME=builder-user
    - BUILD=$BUILD_ID
    # Run a script from the local build context in a Docker container 
    #- COMMAND=/home/basma_boulekhras/workspace/deploy-script.sh $BRANCH_NAME $BUILD_ID ${_RELEASE_NAME} ${_PATH_CHART}  
    - COMMAND=/home/builder-user/workspace/deploy-script.sh 

substitutions:
    _RELEASE_NAME: 'backend'
    _PATH_CHART: 'k8s/contacts-service/'
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
